export class Acta {

    constructor(
      public dniInscripto: number,
      public nombreInscripto: string,
      public apellidoInscripto: string,
      public sexoInscripto: string,
      public fechaNacimientoInscripto: Date,
      public fechaInscripcionInscripto: Date,
      public provinciaInscripto: string,
      public departamentoInscripto: string,
      public localidadInscripto: string,
      public barrioInscripto: string,
      public calleInscripto: string,
      public numeroCalleInscripto: number,
      public nombreObstetra: string,
      public apellidoObstetra: string,
      public nombreClinica: string,
      public tipoClinica: boolean,
      public dniMadre: number,
      public nombreMadre: string,
      public apellidoMadre: string,
      public sexoMadre: boolean,
      public fechaNacimientoMadre: Date,
      public provinciaMadre: string,
      public departamentoMadre: string,
      public localidadMadre: string,
      public barrioMadre: string,
      public calleMadre: string,
      public numeroCalleMadre: number,
      public dniPadre: number,
      public nombrePadre: string,
      public apellidoPadre: string,
      public sexoPadre: boolean,
      public fechaNacimientoPadre: Date,
      public provinciaPadre: string,
      public departamentoPadre: string,
      public localidadPadre: string,
      public barrioPadre: string,
      public callePadre: string,
      public numeroCallePadre: number
    ) {  }
  
  }