export class Acta{
    tomo!: String;
    acta!: String;
    anio!: String;
    lomo!: String;
    delegacion!: String;
    dniInscripto!: String;
    sexo!: String;
    nombreInscripto!: String;
    apellidoInscripto!: String;
    fechaNacimientoInscripto!: String;
    horaNacimiento!: String;
    fechaInscripcion!: String;
    localidadInscripto!: String;
    idObstetra!:String;
    nombreObstetra!: String;
    apellidoObstetra!: String;
    clinica!: String;
    tipoClinica!: String;
    idMadre!:String;
    dniMadre!: String;
    nombreMadre!: String;
    apellidoMadre!: String;
    domicilioMadre!: String;
    idPadre!: String;
    dniPadre!: String;
    nombrePadre!: String;
    apellidoPadre!: String;
    domicilioPadre!: String;
    declarantes!: String;
    observaciones!: String;
}